package com.hardtechnologycreator.simplefilemanager;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

public class SaveFileActivity extends AppCompatActivity {

    private EditText editText;
    private String filename = "", probablyFilename = "";
    private Button btnOk, btnCancel;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_save_file);

        editText = (EditText) findViewById(R.id.editText);
        probablyFilename = editText.getText().toString().replaceAll("\\W", "");

        filename = editText.getText().toString();
        if (!filename.equals(probablyFilename)) {
            Toast.makeText(this, "Wrong file name. \nSee autogenerated name", Toast.LENGTH_LONG).show();
            editText.setText(probablyFilename);
        }

        btnOk = (Button) findViewById(R.id.dialogButtonOk);
        btnOk.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (!filename.equals(probablyFilename)) {
                    Toast.makeText(getApplicationContext(), "Wrong file name. \nSee autogenerated name", Toast.LENGTH_LONG).show();
                    editText.setText(probablyFilename);
                } else {
                    Intent intent = new Intent();
                    intent.putExtra("FileName", filename);
                    setResult(RESULT_OK);
                    finish();
                }

            }
        });

        btnCancel = (Button) findViewById(R.id.dialogButtonCancel);
        btnCancel.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                setResult(RESULT_CANCELED);
                finish();
            }
        });
    }
}
